# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d0df2f38723726223d622a94a38285db3999fdadfb2e9dd2d3f4baac93cf9e236a3bb10226a7faeb16b4bd03f1c185a087f638668e8d5b24ea85ccdd248e01e

test:
  secret_key_base: 241972640d4559ff2cd330f668530b34a3a4ddea1d5622645d1c5c7bd17b34856adfd5107f98309042df44a83266d0e8798ee780e64eb1926bff7a218fa02379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
